### PR TITLE
Readme changes and minor fix.

### PR DESCRIPTION
**Pull request by okrupesh**
Moved a ".md" file to the contributors folder and added redirection to translations page and contributors image in the readme file.

### CODE REVIEW

**Comment by okrupesh** [comment]
@geoffreylgv check if this is okay?

**Comment by geoffreylgv** [comment]
> @geoffreylgv check if this is okay?

Alright @okrupesh, let check it

**Comment by okrupesh** [comment]
> > @geoffreylgv check if this is okay?
> 
> Alright @okrupesh, let check it

Push it if you find this okay... 🙂

**Review by geoffreylgv — APPROVED** [review]
Alright, let's do it 👍🏾

**Pull request merged**
